// Sample data for courses, events, and groups when database is not connected

export const sampleCourses = [
  {
    id: "1",
    title: "Introduction to Permaculture Design",
    description:
      "Learn the fundamentals of permaculture design and how to create sustainable food systems. Perfect for beginners transitioning from tech careers.",
    category: "farming",
    level: "beginner",
    duration: "8 weeks",
    price: 299,
    instructor: "Sarah Chen",
    instructor_title: "Former Software Engineer, now Permaculture Designer",
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-01-15T00:00:00Z",
    content: "This comprehensive course will teach you the principles of permaculture design, including site analysis, water management, soil building, plant guilds, and sustainable food production systems. You'll learn how to apply your tech skills to agricultural planning and design.",
  },
  {
    id: "2",
    title: "Farm-to-Table Restaurant Management",
    description:
      "Master the skills needed to run a successful farm-to-table restaurant. Learn sourcing, menu design, and operations from former tech professionals who made the switch.",
    category: "restaurant",
    level: "intermediate",
    duration: "10 weeks",
    price: 499,
    instructor: "Michael Rodriguez",
    instructor_title: "Former Product Manager, now Restaurant Owner",
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-01-20T00:00:00Z",
    content: "Dive deep into the world of farm-to-table restaurants. Learn about sourcing local ingredients, menu planning, seasonal cooking, restaurant operations, staff management, and building relationships with local farmers and producers.",
  },
  {
    id: "3",
    title: "Sustainable Agriculture Business Planning",
    description:
      "Develop a comprehensive business plan for your sustainable agriculture venture. Learn from experienced farmers who transitioned from tech.",
    category: "business",
    level: "advanced",
    duration: "6 weeks",
    price: 399,
    instructor: "David Park",
    instructor_title: "Former UX Designer, now Farm Owner",
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-02-01T00:00:00Z",
    content: "Develop a comprehensive business plan for your sustainable agriculture venture. Topics include market analysis, financial projections, grant applications, land acquisition, equipment planning, and building a sustainable business model.",
  },
  {
    id: "4",
    title: "Woodworking Fundamentals for Career Changers",
    description:
      "Start your journey into woodworking and furniture making. Learn essential skills and safety practices from craftsmen who left tech careers.",
    category: "crafts",
    level: "beginner",
    duration: "12 weeks",
    price: 449,
    instructor: "Emma Thompson",
    instructor_title: "Former Data Analyst, now Master Carpenter",
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-02-10T00:00:00Z",
    content: "Start your woodworking journey with comprehensive training in tools, safety, joinery techniques, and project planning. Build real projects while learning the fundamentals of furniture making and carpentry.",
  },
  {
    id: "5",
    title: "Organic Vegetable Farming Intensive",
    description:
      "Deep dive into organic vegetable production with hands-on training. Perfect for tech professionals ready to start their own farm.",
    category: "farming",
    level: "intermediate",
    duration: "16 weeks",
    price: 699,
    instructor: "James Liu",
    instructor_title: "Former DevOps Engineer, now Organic Farmer",
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-02-15T00:00:00Z",
    content: "Intensive hands-on training in organic vegetable production. Learn crop planning, succession planting, pest management, harvest and post-harvest handling, and direct marketing to customers.",
  },
  {
    id: "6",
    title: "Artisanal Bread Baking & Bakery Operations",
    description:
      "Learn the art of bread baking and how to operate a successful bakery business. Taught by former tech professionals who became master bakers.",
    category: "restaurant",
    level: "beginner",
    duration: "8 weeks",
    price: 349,
    instructor: "Lisa Anderson",
    instructor_title: "Former Frontend Developer, now Bakery Owner",
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-02-20T00:00:00Z",
    content: "Master the art of artisanal bread baking, from sourdough starters to specialty breads. Learn bakery operations, equipment management, production scheduling, and building a successful bakery business.",
  },
]

export const sampleEvents = [
  {
    id: "1",
    title: "Urban Farm Tour & Networking Mixer",
    description:
      "Visit a thriving urban farm run by a former software engineer and connect with other tech professionals making the transition to agriculture.",
    category: "farm-tour",
    start_date: "2024-12-15T10:00:00Z",
    end_date: "2024-12-15T15:00:00Z",
    location: "Green Valley Urban Farm, San Francisco, CA",
    price: 0,
    capacity: 30,
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-11-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Hands-On Permaculture Workshop",
    description:
      "Full-day workshop covering soil building, composting, and garden design. Get your hands dirty and learn practical skills!",
    category: "workshop",
    start_date: "2024-12-20T09:00:00Z",
    end_date: "2024-12-20T17:00:00Z",
    location: "Earthwise Farm, Portland, OR",
    price: 75,
    max_attendees: 25,
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-11-05T00:00:00Z",
  },
  {
    id: "3",
    title: "Tech-to-Earth Career Fair",
    description:
      "Meet employers from farms, restaurants, and sustainable businesses looking to hire people with tech backgrounds.",
    category: "job-fair",
    start_date: "2025-01-10T10:00:00Z",
    end_date: "2025-01-10T16:00:00Z",
    location: "Green Convention Center, Austin, TX",
    price: 0,
    max_attendees: 200,
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-11-10T00:00:00Z",
  },
  {
    id: "4",
    title: "Restaurant Kitchen Bootcamp",
    description:
      "Intensive weekend workshop for aspiring restaurant workers. Learn knife skills, food prep, and kitchen operations.",
    category: "workshop",
    start_date: "2025-01-18T08:00:00Z",
    end_date: "2025-01-19T18:00:00Z",
    location: "Culinary Institute, Boulder, CO",
    price: 150,
    max_attendees: 20,
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-11-15T00:00:00Z",
  },
  {
    id: "5",
    title: "Monthly Tech Refugees Meetup",
    description:
      "Casual monthly gathering for tech professionals exploring earth-based careers. Share experiences, ask questions, and build community.",
    category: "networking",
    start_date: "2025-01-25T18:00:00Z",
    end_date: "2025-01-25T21:00:00Z",
    location: "Green Café, Seattle, WA",
    price: 0,
    max_attendees: 50,
    image_url: "/placeholder.svg",
    is_published: true,
    created_at: "2024-11-20T00:00:00Z",
  },
]

export const sampleGroups = [
  {
    id: "1",
    name: "SF Bay Area Tech to Farm Collective",
    description:
      "A community of former tech workers now farming in the Bay Area. We share resources, equipment, and knowledge while supporting each other's transitions.",
    category: "farming",
    location: "San Francisco Bay Area, CA",
    member_count: 156,
    image_url: "/placeholder.svg",
    created_at: "2023-06-15T00:00:00Z",
  },
  {
    id: "2",
    name: "Restaurant Career Changers",
    description:
      "Support group for people transitioning from corporate jobs to the restaurant industry. We share job leads, training opportunities, and moral support!",
    category: "food",
    location: "Online + NYC",
    member_count: 243,
    image_url: "/placeholder.svg",
    created_at: "2023-08-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Digital Detox Farmers",
    description:
      "Former tech professionals who left screen time for green time. Share your farming journey, challenges, and victories with those who understand.",
    category: "farming",
    location: "Pacific Northwest",
    member_count: 89,
    image_url: "/placeholder.svg",
    created_at: "2023-09-10T00:00:00Z",
  },
  {
    id: "4",
    name: "Sustainable Living Network",
    description:
      "Building a sustainable lifestyle beyond tech. Discuss permaculture, renewable energy, zero waste, and living in harmony with nature.",
    category: "sustainability",
    location: "Online",
    member_count: 412,
    image_url: "/placeholder.svg",
    created_at: "2023-07-20T00:00:00Z",
  },
  {
    id: "5",
    name: "Artisan Makers Guild",
    description:
      "Tech professionals turned craftspeople. Woodworking, metalworking, pottery, and more. Share techniques, tools, and business advice.",
    category: "crafts",
    location: "Online + Regional Chapters",
    member_count: 178,
    image_url: "/placeholder.svg",
    created_at: "2023-10-05T00:00:00Z",
  },
  {
    id: "6",
    name: "Farm-to-Table Entrepreneurs",
    description:
      "Network for those building farm-to-table businesses. From CSAs to restaurants, share insights on sourcing, operations, and customer relationships.",
    category: "food",
    location: "Online",
    member_count: 134,
    image_url: "/placeholder.svg",
    created_at: "2023-11-12T00:00:00Z",
  },
]

